[build]
  command = "npm run build"
  publish = "out"

# Next.jsプラグインをスキップ
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Netlifyでのページリロード時に404エラーを回避するための設定
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 